# site settings
title: TK
subtitle: 
email: tkillia2@nd.edu
description: A site to learn more about me, Tommy.<br /> You can read about my work, projects, and more! 
baseurl: "" # the subpath of your site, e.g. /blog
url: 
author: Thomas Killian
street_address: 23 Shoal Creek Ct
city: Bloomington
state: IL
zip_code: 61704
country: United States of America
phone: (309)-445-1666

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tkillia2
  GitLab: 
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/thomaskillian
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

plugins:
- jekyll-seo-tag